/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Todo App API
 * An API for managing todo items
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { axiosInstance } from "./axiosInstance";
export interface PostTodo {
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  id?: number | string | null;
  title?: string;
  description?: string;
  isCompleted?: boolean;
  category?: string;
  color?: string;
}

export interface TodoItem {
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  id?: number | string | null;
  title?: string;
  description?: string;
  isCompleted?: boolean;
  category?: string;
  color?: string;
  createdAt?: string;
}

export interface UpdateTodo {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  title?: string;
  description?: string;
  isCompleted?: boolean;
  category?: string;
  color?: string;
}

export const getApiTodo = (signal?: AbortSignal) => {
  return axiosInstance<TodoItem[]>({ url: `/api/Todo`, method: "GET", signal });
};

export const getGetApiTodoMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof getApiTodo>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof getApiTodo>>, TError, void, TContext> => {
  const mutationKey = ["getApiTodo"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiTodo>>, void> = () => {
    return getApiTodo();
  };

  return { mutationFn, ...mutationOptions };
};

export type GetApiTodoMutationResult = NonNullable<Awaited<ReturnType<typeof getApiTodo>>>;

export type GetApiTodoMutationError = unknown;

export const useGetApiTodo = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof getApiTodo>>, TError, void, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof getApiTodo>>, TError, void, TContext> => {
  return useMutation(getGetApiTodoMutationOptions(options), queryClient);
};

export const postApiTodo = (postTodo: PostTodo, signal?: AbortSignal) => {
  return axiosInstance<boolean>({
    url: `/api/Todo`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postTodo,
    signal,
  });
};

export const getPostApiTodoQueryKey = (postTodo?: PostTodo) => {
  return ["POST", `/api/Todo`, postTodo] as const;
};

export const getPostApiTodoQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiTodo>>,
  TError = unknown,
>(
  postTodo: PostTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiTodo>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPostApiTodoQueryKey(postTodo);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiTodo>>> = ({ signal }) =>
    postApiTodo(postTodo, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiTodo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiTodoQueryResult = NonNullable<Awaited<ReturnType<typeof postApiTodo>>>;
export type PostApiTodoQueryError = unknown;

export function usePostApiTodo<TData = Awaited<ReturnType<typeof postApiTodo>>, TError = unknown>(
  postTodo: PostTodo,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiTodo>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiTodo>>,
          TError,
          Awaited<ReturnType<typeof postApiTodo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiTodo<TData = Awaited<ReturnType<typeof postApiTodo>>, TError = unknown>(
  postTodo: PostTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiTodo>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiTodo>>,
          TError,
          Awaited<ReturnType<typeof postApiTodo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiTodo<TData = Awaited<ReturnType<typeof postApiTodo>>, TError = unknown>(
  postTodo: PostTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiTodo>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePostApiTodo<TData = Awaited<ReturnType<typeof postApiTodo>>, TError = unknown>(
  postTodo: PostTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiTodo>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPostApiTodoQueryOptions(postTodo, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const putApiTodoId = (id: number | string, updateTodo: UpdateTodo, signal?: AbortSignal) => {
  return axiosInstance<boolean>({
    url: `/api/Todo/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateTodo,
    signal,
  });
};

export const getPutApiTodoIdQueryKey = (id: number | string, updateTodo?: UpdateTodo) => {
  return ["PUT", `/api/Todo/${id}`, updateTodo] as const;
};

export const getPutApiTodoIdQueryOptions = <
  TData = Awaited<ReturnType<typeof putApiTodoId>>,
  TError = unknown,
>(
  id: number | string,
  updateTodo: UpdateTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiTodoId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPutApiTodoIdQueryKey(id, updateTodo);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiTodoId>>> = ({ signal }) =>
    putApiTodoId(id, updateTodo, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof putApiTodoId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type PutApiTodoIdQueryResult = NonNullable<Awaited<ReturnType<typeof putApiTodoId>>>;
export type PutApiTodoIdQueryError = unknown;

export function usePutApiTodoId<TData = Awaited<ReturnType<typeof putApiTodoId>>, TError = unknown>(
  id: number | string,
  updateTodo: UpdateTodo,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiTodoId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiTodoId>>,
          TError,
          Awaited<ReturnType<typeof putApiTodoId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiTodoId<TData = Awaited<ReturnType<typeof putApiTodoId>>, TError = unknown>(
  id: number | string,
  updateTodo: UpdateTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiTodoId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiTodoId>>,
          TError,
          Awaited<ReturnType<typeof putApiTodoId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiTodoId<TData = Awaited<ReturnType<typeof putApiTodoId>>, TError = unknown>(
  id: number | string,
  updateTodo: UpdateTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiTodoId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePutApiTodoId<TData = Awaited<ReturnType<typeof putApiTodoId>>, TError = unknown>(
  id: number | string,
  updateTodo: UpdateTodo,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiTodoId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPutApiTodoIdQueryOptions(id, updateTodo, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const deleteApiTodoId = (id: number | string, signal?: AbortSignal) => {
  return axiosInstance<boolean>({ url: `/api/Todo/${id}`, method: "DELETE", signal });
};

export const getDeleteApiTodoIdQueryKey = (id: number | string) => {
  return ["DELETE", `/api/Todo/${id}`] as const;
};

export const getDeleteApiTodoIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiTodoId>>,
  TError = unknown,
>(
  id: number | string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiTodoId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDeleteApiTodoIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiTodoId>>> = ({ signal }) =>
    deleteApiTodoId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof deleteApiTodoId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type DeleteApiTodoIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiTodoId>>>;
export type DeleteApiTodoIdQueryError = unknown;

export function useDeleteApiTodoId<
  TData = Awaited<ReturnType<typeof deleteApiTodoId>>,
  TError = unknown,
>(
  id: number | string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiTodoId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiTodoId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiTodoId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDeleteApiTodoId<
  TData = Awaited<ReturnType<typeof deleteApiTodoId>>,
  TError = unknown,
>(
  id: number | string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiTodoId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiTodoId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiTodoId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDeleteApiTodoId<
  TData = Awaited<ReturnType<typeof deleteApiTodoId>>,
  TError = unknown,
>(
  id: number | string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiTodoId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDeleteApiTodoId<
  TData = Awaited<ReturnType<typeof deleteApiTodoId>>,
  TError = unknown,
>(
  id: number | string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiTodoId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDeleteApiTodoIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const get = (signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/`, method: "GET", signal });
};

export const getGetMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof get>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof get>>, TError, void, TContext> => {
  const mutationKey = ["get"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof get>>, void> = () => {
    return get();
  };

  return { mutationFn, ...mutationOptions };
};

export type GetMutationResult = NonNullable<Awaited<ReturnType<typeof get>>>;

export type GetMutationError = unknown;

export const useGet = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof get>>, TError, void, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof get>>, TError, void, TContext> => {
  return useMutation(getGetMutationOptions(options), queryClient);
};
